### ISSUE TITLE
Remove button hover opacity

### ISSUE THREAD

**Issue by amdelamar** [amdelamar/osseous#11]
It interferes with dropdowns and tabs.

**Comment by amdelamar** [comment]
A better alternative to setting opacity is to use a box shadow like so:

```css
.button:hover {
  box-shadow: inset 0 0 100px 100px rgba(255, 255, 255, 0.1);
}
```
