### ISSUE TITLE
Make shadow angled as if it were from light

### ISSUE THREAD

**Issue by amdelamar** [amdelamar/osseous#15]
```css
/* Angled from light source, upper left */
.shadow, .hover-shadow:hover {
  box-shadow: 0 4px 4px 0 rgba(0,0,0,0.15) !important;
}

/* Evenly glowing on all sides */
.shadow-outline, .hover-shadow-outline:hover {
  box-shadow: 0 0 4px 1px rgba(0,0,0,0.15) !important;
}
```
