### ISSUE TITLE
Add show/hide classes on sm/md/lg

### ISSUE THREAD

**Issue by amdelamar** [amdelamar/osseous#18]
Something like:

```css
@media only screen and (max-width: 600px) {
  .sm-hide {
    display: none;
  }
}
```
