### ISSUE TITLE
Add Tabs

### ISSUE THREAD

**Issue by amdelamar** [amdelamar/osseous#6]
```css
.tabs {
  padding: 0;
  margin: auto;
  align-items: flex-end;
  height: 100%;
  min-height: 6.5rem;
  display: flex;
  flex-direction: row;
  justify-content: flex-start;
}
.tabs .tab {
  background: transparent;
  border: 1px solid var(--grey);
  border-bottom: unset;
  border-right: unset;
  margin: 0;
  border-top-left-radius: 1rem;
  border-top-right-radius: 1rem;
  border-bottom-left-radius: 0;
  border-bottom-right-radius: 0;
}
.tabs .tab:last-child {
  border-right: 1px solid var(--grey);
}
.tabs .tab:hover {
  background: var(--white) !important;
}
.tabs .tab.router-link-exact-active, .tabs .tab.active {
  background: var(--white);
}
```
