### ISSUE TITLE
Add button outline variants

### ISSUE THREAD

**Issue by amdelamar** [amdelamar/osseous#7]
Something like... but in place of regular `button-blue`

```css
.button-blue-outline {
  background: transparent;
  color: var(--blue);
}
.button-red-outline {
  background: transparent;
  color: var(--red);
}
.button-green-outline {
  background: transparent;
  color: var(--green);
}
```

Note: Should be done after "blue/red/green" classes are renamed
