### ISSUE TITLE
Dropdown body on alternate background color

### ISSUE THREAD

**Issue by amdelamar** [amdelamar/osseous#8]
The dropdown body background color should default to its parent's background color.

```css
.dropdown-body {
  font-size: initial;
  font-weight: initial;
  line-height: initial;
  letter-spacing: initial;
  text-transform: initial;
}
```
